[package]
name = "pran-droid-persistence-sea-orm-entities"
version = "0.1.0"
authors = ["Pmyl <julo134@gmail.com>"]
edition = "2021"

[dependencies]
sea-orm = { version = "0.8.0", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }