[package]
name = "pran-echo-core"
version = "0.1.0"
authors = ["Pmyl <julo134@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.14.2", features = ["extension-module"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket-multipart-form-data = "0.10.0"
serde = "1.0.128"
uuid = { version = "0.8.2", features = ["v4"] }
dotenv = "0.15.0"