export const testPhonemesMap: Map<string, string[]> = new Map<string, string[]>([
  // consonants
  ['b', ['mbsilent']],
  ['d', ['ld']],
  ['f', ['fv']],
  ['g', ['stch']],
  ['h', ['ur']],
  ['dʒ', ['stch']],
  ['k', ['stch']],
  ['l', ['ld']],
  ['m', ['mbsilent']],
  ['n', ['mbsilent']],
  ['p', ['p1', 'p2']],
  ['r', ['ur']],
  ['s', ['stch']],
  ['t', ['stch']],
  ['v', ['fv']],
  ['w', ['ur']],
  ['z', ['stch']],
  ['ʒ', ['stch']],
  ['tʃ', ['stch']],
  ['ʃ', ['stch']],
  ['θ', ['stch']],
  ['ð', ['stch']],
  ['ŋ', ['mbsilent']],
  ['j', ['stch']],

  // vowels
  ['æ', ['aah']],
  ['eɪ', ['e']],
  ['e', ['e']],
  ['i:', ['e']],
  ['ɪ', ['e']],
  ['aɪ', ['aah']],
  ['ɒ', ['aah']],
  ['oʊ', ['o']],
  ['ʊ', ['ur']],
  ['ʌ', ['aah']],
  ['u:', ['ur']],
  ['ɔɪ', ['o']],
  ['aʊ', ['aah']],
  ['ə', ['aah']],
  ['eəʳ', ['aah']],
  ['ɑ:', ['aah']],
  ['ɜ:ʳ', ['ur']],
  ['ɔ:', ['aah']],
  ['ɪəʳ', ['e']],
  ['ʊəʳ', ['ur']],

  // punctuation
  [',', ['pause']],
  ['.', ['pause', 'smile']],
]);