[package]
name = "pran-droid-core"
version = "0.1.0"
authors = ["Pmyl <julo134@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.56"
log = "0.4.17"
rand = "0.8.5"
thiserror = "1.0.30"
uuid = { version = "0.8.2", features = ["v4"] }