export const SPEECH_BUBBLE_CANVAS_WIDTH = 500;
export const SPEECH_BUBBLE_CANVAS_HEIGHT = 200;
export const SPEECH_BUBBLE_PADDING = 15;
export const SPEECH_BUBBLE_MARGIN = 25;
export const MAX_SPEECH_BUBBLE_WIDTH = SPEECH_BUBBLE_CANVAS_WIDTH - SPEECH_BUBBLE_PADDING * 2 - SPEECH_BUBBLE_MARGIN * 2;

export const SPEECH_BUBBLE_INSIDE_COLOR = '#EAC315';
export const SPEECH_BUBBLE_BORDER_COLOR = '#BBB';
export const SPEECH_BUBBLE_BORDER_LINE_WIDTH = 3;
export const SPEECH_BUBBLE_BORDER_RADIUS = 20;
export const SPEECH_BUBBLE_ARROW_HEIGHT = 30;
export const SPEECH_BUBBLE_ARROW_WIDTH = 30;
export const SPEECH_BUBBLE_ARROW_X = SPEECH_BUBBLE_CANVAS_WIDTH / 2 - SPEECH_BUBBLE_ARROW_WIDTH / 2;
export const SPEECH_BUBBLE_FONT_SIZE = 20;
export const LETTER_DURATION = 50;