[package]
name = "pran-phonemes-core"
version = "0.1.0"
authors = ["Pmyl <julo134@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.14.2"
dotenv = "0.15.0"
