name: Create Pran Droid Brain Console release

on:
  push:
    branches:
      - main
    paths:
      - pran-droid/brain/**
      - pran-droid/brain_console/**
      - pran-droid/core/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo build --manifest-path ./pran-droid/brain_console/Cargo.toml --release
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: v0.1.0-brain-console-release
          name: Brain console release
          files: ./pran-droid/brain_console/target/release/brain_console.exe