name: Deploy Pran Droid Api to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "pran-droid-api"
          dockerfile_directory: .
          dockerfile_name: ./.deploy/pran-droid/api/Dockerfile
          docker_options: "--no-cache"